"cs_prison"
{
   "name" "cs_prison"
   "t_arms" "models/weapons/t_arms_phoenix.mdl"
   "ct_arms" "models/weapons/ct_arms.mdl"
   "t_models"
   {
      "tm_phoenix"""
		"tm_phoenix_variantA"""
		"tm_phoenix_variantB"""
		"tm_phoenix_variantC"""
		"tm_phoenix_variantD"""
   }
   "ct_models"
   {
      "ctm_st6"""
		"ctm_st6_variantA"""
		"ctm_st6_variantB"""
		"ctm_st6_variantC"""
		"ctm_st6_variantD"""
   }
}