"de_rust_b2"
{
	"nameID"			"#SFUI_Map_de_wares"
	"name"				"de_rust_b2"
	"imagename"			"de_rust_b2"
	"t_arms"			"models/weapons/t_arms_leet.mdl"
	"t_models"
	{
		"tm_phoenix"		""
		"tm_phoenix_variantA"	""
		"tm_phoenix_variantB"	""
		"tm_phoenix_variantC"	""
		"tm_phoenix_variantD"	""
	}
	"ct_arms"			"models/weapons/ct_arms_fbi.mdl"
	"ct_models"
	{
		"ctm_fbi"		""
		"ctm_fbi_variantA"	""
		"ctm_fbi_variantB"	""
		"ctm_fbi_variantC"	""
		"ctm_fbi_variantD"	""
	}
}