"de_tokyocomplex"
{
   "name" "de_tokyocomplex"
   "t_arms" "models/weapons/t_arms_anarchist.mdl"
   "ct_arms" "models/weapons/ct_arms_sas.mdl"
   "t_models"
   {
	"tm_anarchist"""
	"tm_anarchist_variantA"""
	"tm_anarchist_variantB"""
	"tm_anarchist_variantC"""
	"tm_anarchist_variantD"""
   }
   "ct_models"
   {
	"ctm_sas"""
	"ctm_sas_variantA"""
	"ctm_sas_variantB"""
	"ctm_sas_variantC"""
	"ctm_sas_variantD"""
   }
}